language: node_js
matrix:
  include:
    - node_js: node # Current
    - node_js: lts/* # Latest LTS
      env: NPM_DEPLOY=true
    - node_js: lts/carbon # Minimum required (eslint-plugin-strict-vue, etc)
before_script: npm run lint
deploy:
  provider: npm
  email: pro.alexandre.mercier@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    condition: $NPM_DEPLOY = true # Prevents publishing on each matrix build
cache:
  directories:
    - $HOME/.nvm
